name: google_api_availability
description: A Flutter plugin to check the availability of Google Play Services on an Android device.
version: 3.0.0
homepage: https://github.com/baseflowit/flutter-google-api-availability

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.googleapiavailability
        pluginClass: GoogleApiAvailabilityPlugin
