name: google_api_availability
description: A Flutter plugin to check the availability of Google Play Services on an Android device.
version: 3.0.2
homepage: https://github.com/baseflowit/flutter-google-api-availability

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.googleapiavailability
        pluginClass: GoogleApiAvailabilityPlugin
